services:
  # Your other services.

  gotenberg:
    image: gotenberg/gotenberg:8
    ports:
      - "3000:3000"
     # Or more secure:
     # - "127.0.0.1:3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"     